# ============================================
# Sägesteuerung - WT32-SC01 Display mit ESPHome
# Dark Mode UI mit zwei Toggle-Buttons
# (Säge & Absaugung)
# Die Switches leben direkt auf dem Gerät und
# erscheinen automatisch in Home Assistant.
# ============================================
substitutions:
  name: "saegesteuerung"
  friendly_name: "Sägesteuerung"
  id_prefix: "saege"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - display.page.show: main_page

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 15min

logger:
  level: ERROR

api:
  encryption:
    key: !secret ha_defaultkey

ota:
  - platform: esphome
    password: !secret esphome_ota_pw

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pw_iot
  manual_ip:
    static_ip: !secret ip_saegesteuerung
    gateway: !secret ip_iot_gateway
    subnet: !secret ip_iot_subnet
    dns1: !secret ip_iot_dns
  ap:
    ssid: "${name} Fallback"
    password: !secret esphome_fb_pw

# ==================
# Switches (lokal auf dem Gerät)
# Erscheinen automatisch als Entitäten in HA:
#   switch.saegesteuerung_saege
#   switch.saegesteuerung_absaugung
# ==================
switch:
  - platform: template
    name: "Säge"
    id: sw_saege
    icon: "mdi:saw-blade"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - component.update: ${id_prefix}_display
    on_turn_off:
      - component.update: ${id_prefix}_display

  - platform: template
    name: "Absaugung"
    id: sw_absaugung
    icon: "mdi:fan"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - component.update: ${id_prefix}_display
    on_turn_off:
      - component.update: ${id_prefix}_display

# ==================
# Scripts
# ==================
script:
  - id: undim_script
    mode: restart
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - delay: 30s
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 20%

  - id: toggle_switch1
    mode: single
    then:
      - switch.toggle: sw_saege

  - id: toggle_switch2
    mode: single
    then:
      - switch.toggle: sw_absaugung

# ==================
# Time
# ==================
time:
  - platform: homeassistant
    id: homeassistant_time

# ==================
# Backlight
# ==================
output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} Backlight"
    id: ${id_prefix}_backlight
    restore_mode: RESTORE_DEFAULT_OFF

# ==================
# I2C & Touch
# ==================
i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

touchscreen:
  - platform: ft63x6
    id: ${id_prefix}_touch
    i2c_id: i2c_bus_intern
    interrupt_pin: GPIO39
    transform:
      swap_xy: true
      mirror_y: true
    on_touch:
      - script.execute: undim_script

# ==================
# SPI & Display
# ==================
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9xxx
    id: ${id_prefix}_display
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    invert_colors: false
    transform:
      swap_xy: true
    dimensions:
      width: 480
      height: 320
    pages:
      - id: main_page
        lambda: |-
          // =============================
          // SÄGESTEUERUNG - Dark Mode UI
          // Display: 480 x 320 px
          // =============================
          
          // -- Hintergrund (#0A0E14) --
          it.filled_rectangle(0, 0, 480, 320, bg_dark);
          
          // -- Header: "SAEGESTEUERUNG" --
          it.printf(240, 30, id(fntHeader), col_white, TextAlign::TOP_CENTER, "SAEGESTEUERUNG");
          
          // -- Pill-Button Dimensionen --
          uint16_t pill_w = 336;
          uint16_t pill_h = 70;
          uint16_t pill_r = 35;
          uint16_t pill_x = (480 - pill_w) / 2;  // = 72
          uint16_t pill_y1 = 90;   // Erste Kapsel (Säge)
          uint16_t pill_y2 = 200;  // Zweite Kapsel (Absaugung)
          
          uint16_t icon_x = pill_x + 16;
          uint16_t icon_y_offset = (pill_h - 40) / 2;
          uint16_t label_x = pill_x + 70;
          uint16_t status_x = pill_x + pill_w + 12;
          
          // ================================
          // TOGGLE 1: SÄGE (lokaler State)
          // ================================
          bool saege_on = id(sw_saege).state;
          
          if (saege_on) {
            it.filled_circle(pill_x + pill_r, pill_y1 + pill_r, pill_r, col_mint);
            it.filled_circle(pill_x + pill_w - pill_r, pill_y1 + pill_r, pill_r, col_mint);
            it.filled_rectangle(pill_x + pill_r, pill_y1, pill_w - 2 * pill_r, pill_h, col_mint);
            it.image(icon_x, pill_y1 + icon_y_offset, id(imgSaege), bg_dark);
            it.printf(label_x, pill_y1 + pill_h / 2, id(fntButton), bg_dark, TextAlign::CENTER_LEFT, "SAEGE");
            it.printf(status_x, pill_y1 + pill_h / 2, id(fntStatus), col_mint, TextAlign::CENTER_LEFT, "AN");
          } else {
            it.circle(pill_x + pill_r, pill_y1 + pill_r, pill_r, col_mint);
            it.circle(pill_x + pill_w - pill_r, pill_y1 + pill_r, pill_r, col_mint);
            it.line(pill_x + pill_r, pill_y1, pill_x + pill_w - pill_r, pill_y1, col_mint);
            it.line(pill_x + pill_r, pill_y1 + pill_h, pill_x + pill_w - pill_r, pill_y1 + pill_h, col_mint);
            it.image(icon_x, pill_y1 + icon_y_offset, id(imgSaege), col_light_grey);
            it.printf(label_x, pill_y1 + pill_h / 2, id(fntButton), col_white, TextAlign::CENTER_LEFT, "SAEGE");
            it.printf(status_x, pill_y1 + pill_h / 2, id(fntStatus), col_light_grey, TextAlign::CENTER_LEFT, "AUS");
          }
          
          // ================================
          // TOGGLE 2: ABSAUGUNG (lokaler State)
          // ================================
          bool absaug_on = id(sw_absaugung).state;
          
          if (absaug_on) {
            it.filled_circle(pill_x + pill_r, pill_y2 + pill_r, pill_r, col_mint);
            it.filled_circle(pill_x + pill_w - pill_r, pill_y2 + pill_r, pill_r, col_mint);
            it.filled_rectangle(pill_x + pill_r, pill_y2, pill_w - 2 * pill_r, pill_h, col_mint);
            it.image(icon_x, pill_y2 + icon_y_offset, id(imgAbsaugung), bg_dark);
            it.printf(label_x, pill_y2 + pill_h / 2, id(fntButton), bg_dark, TextAlign::CENTER_LEFT, "ABSAUGUNG");
            it.printf(status_x, pill_y2 + pill_h / 2, id(fntStatus), col_mint, TextAlign::CENTER_LEFT, "AN");
          } else {
            it.circle(pill_x + pill_r, pill_y2 + pill_r, pill_r, col_mint);
            it.circle(pill_x + pill_w - pill_r, pill_y2 + pill_r, pill_r, col_mint);
            it.line(pill_x + pill_r, pill_y2, pill_x + pill_w - pill_r, pill_y2, col_mint);
            it.line(pill_x + pill_r, pill_y2 + pill_h, pill_x + pill_w - pill_r, pill_y2 + pill_h, col_mint);
            it.image(icon_x, pill_y2 + icon_y_offset, id(imgAbsaugung), col_light_grey);
            it.printf(label_x, pill_y2 + pill_h / 2, id(fntButton), col_white, TextAlign::CENTER_LEFT, "ABSAUGUNG");
            it.printf(status_x, pill_y2 + pill_h / 2, id(fntStatus), col_light_grey, TextAlign::CENTER_LEFT, "AUS");
          }
          
          // -- Trennlinie zwischen den Buttons --
          it.line(100, 175, 380, 175, col_dark_grey);
          
          // -- WiFi-Status unten links --
          uint16_t wfx = 10;
          uint16_t wfy = 290;
          if (id(${id_prefix}_wifi).has_state()) {
            if (id(${id_prefix}_wifi).state < -70) {
              it.image(wfx, wfy, id(wifi1), col_yellow);
            } else if (id(${id_prefix}_wifi).state < -60) {
              it.image(wfx, wfy, id(wifi2), col_mint);
            } else if (id(${id_prefix}_wifi).state < -50) {
              it.image(wfx, wfy, id(wifi3), col_mint);
            } else {
              it.image(wfx, wfy, id(wifi4), col_mint);
            }
          } else {
            it.image(wfx, wfy, id(wifi0), col_red);
          }

# ==================
# Fonts
# ==================
font:
  - file:
      type: gfonts
      family: "Roboto Condensed"
      weight: bold
    id: fntHeader
    size: 32
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü0123456789 .-:!?"
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fntButton
    size: 28
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü0123456789 .-:!?"
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fntStatus
    size: 22
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü0123456789 .-:!?"

# ==================
# Colors
# ==================
color:
  - id: bg_dark
    red: 4%
    green: 5%
    blue: 8%
  - id: col_mint
    red: 10%
    green: 74%
    blue: 61%
  - id: col_white
    red: 100%
    green: 100%
    blue: 100%
  - id: col_light_grey
    red: 65%
    green: 65%
    blue: 65%
  - id: col_dark_grey
    red: 25%
    green: 25%
    blue: 30%
  - id: col_red
    red: 100%
    green: 25%
    blue: 25%
  - id: col_yellow
    red: 75%
    green: 75%
    blue: 0%

# ==================
# Images (MDI Icons)
# ==================
image:
  - file: mdi:saw-blade
    id: imgSaege
    resize: 40x40
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:fan
    id: imgAbsaugung
    resize: 40x40
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:wifi-strength-alert-outline
    id: wifi0
    resize: 24x24
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:wifi-strength-1
    id: wifi1
    resize: 24x24
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:wifi-strength-2
    id: wifi2
    resize: 24x24
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:wifi-strength-3
    id: wifi3
    resize: 24x24
    dither: FLOYDSTEINBERG
    type: GRAYSCALE
  - file: mdi:wifi-strength-4
    id: wifi4
    resize: 24x24
    dither: FLOYDSTEINBERG
    type: GRAYSCALE

# ==================
# Sensors
# ==================
sensor:
  - platform: wifi_signal
    name: "${id_prefix}_wifi"
    id: "${id_prefix}_wifi"
    internal: true
    update_interval: 10s

# ==================
# Binary Sensors (Touch-Bereiche)
# ==================
binary_sensor:
  - <<: !include
      file: includes/iTouch2.yaml
      vars:
        iId: "touch_saege"
        iPg: "main_page"
        iX1: "60"
        iX2: "420"
        iY1: "80"
        iY2: "170"
        iSc: "toggle_switch1"
  - <<: !include
      file: includes/iTouch2.yaml
      vars:
        iId: "touch_absaugung"
        iPg: "main_page"
        iX1: "60"
        iX2: "420"
        iY1: "190"
        iY2: "280"
        iSc: "toggle_switch2"
