# ============================================
# Sägesteuerung - WT32-SC01 Display mit ESPHome
# Optimiert für minimale CPU-Last & schnelle Reaktion
#
# Nutzung als Remote-Package:
#   packages:
#     saege:
#       url: https://github.com/linbo24/wt32sc01-with-esphome
#       ref: main
#       files:
#         - saegesteuerung.yaml
# ============================================

substitutions:
  name: "saegesteuerung"
  friendly_name: "Sägesteuerung"
  id_prefix: "saege"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - display.page.show: main_page

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

psram:
  mode: quad
  speed: 80MHz

preferences:
  flash_write_interval: 60min

logger:
  level: WARN
  baud_rate: 0

api:

ota:
  - platform: esphome
    password: !secret esphome_ota_pw

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pw_iot
  power_save_mode: NONE
  manual_ip:
    static_ip: !secret ip_saegesteuerung
    gateway: !secret ip_iot_gateway
    subnet: !secret ip_iot_subnet
    dns1: !secret ip_iot_dns
  ap:
    ssid: "${name} Fallback"
    password: !secret esphome_fb_pw

# ==================
# Globals fuer Slide-Animation
# anim_step: 0 = idle, 1..6 = Animationsframe
# anim_dir:  1 = slide rechts (AN), -1 = slide links (AUS)
# ==================
globals:
  - id: anim_step_1
    type: int
    initial_value: '0'
  - id: anim_dir_1
    type: int
    initial_value: '1'
  - id: anim_step_2
    type: int
    initial_value: '0'
  - id: anim_dir_2
    type: int
    initial_value: '1'

switch:
  - platform: template
    name: "Säge"
    id: sw_saege
    icon: "mdi:saw-blade"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - globals.set: {id: anim_dir_1, value: '1'}
      - globals.set: {id: anim_step_1, value: '1'}
      - script.execute: animate_1
    on_turn_off:
      - globals.set: {id: anim_dir_1, value: '-1'}
      - globals.set: {id: anim_step_1, value: '1'}
      - script.execute: animate_1

  - platform: template
    name: "Absaugung"
    id: sw_absaugung
    icon: "mdi:fan"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - globals.set: {id: anim_dir_2, value: '1'}
      - globals.set: {id: anim_step_2, value: '1'}
      - script.execute: animate_2
    on_turn_off:
      - globals.set: {id: anim_dir_2, value: '-1'}
      - globals.set: {id: anim_step_2, value: '1'}
      - script.execute: animate_2

script:
  - id: undim_script
    mode: restart
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - delay: 30s
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 20%

  - id: toggle_switch1
    mode: single
    then:
      - switch.toggle: sw_saege

  - id: toggle_switch2
    mode: single
    then:
      - switch.toggle: sw_absaugung

  # Slide-Animation Switch 1: 5 Frames, nur bei Toggle
  - id: animate_1
    mode: restart
    then:
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_1, value: '2'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_1, value: '3'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_1, value: '4'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_1, value: '5'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_1, value: '0'}
      - component.update: ${id_prefix}_display

  # Slide-Animation Switch 2: 5 Frames, nur bei Toggle
  - id: animate_2
    mode: restart
    then:
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_2, value: '2'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_2, value: '3'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_2, value: '4'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_2, value: '5'}
      - component.update: ${id_prefix}_display
      - delay: 30ms
      - globals.set: {id: anim_step_2, value: '0'}
      - component.update: ${id_prefix}_display

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} Backlight"
    id: ${id_prefix}_backlight
    restore_mode: RESTORE_DEFAULT_OFF

i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

touchscreen:
  - platform: ft63x6
    id: ${id_prefix}_touch
    i2c_id: i2c_bus_intern
    interrupt_pin: GPIO39
    transform:
      swap_xy: true
      mirror_y: true
    on_touch:
      - script.execute: undim_script

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9xxx
    id: ${id_prefix}_display
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    invert_colors: false
    transform:
      swap_xy: true
    dimensions:
      width: 480
      height: 320
    update_interval: never
    pages:
      - id: main_page
        lambda: |-
          // ========================================
          // SAEGESTEUERUNG – Slider-Toggle Dark UI
          // 480x320, Landscape
          // ========================================
          it.fill(bg_dark);
          
          // ---- Header ----
          it.print(240, 20, id(fnt28), col_white, TextAlign::TOP_CENTER, "SAEGESTEUERUNG");
          
          // ---- Slider-Toggle Dimensions ----
          // Track: die lange Pill-Bahn
          // Knob: der runde Slider-Kreis
          int tx = 50;           // Track links-X
          int tw = 380;          // Track Breite
          int th = 70;           // Track Hoehe
          int tr = th / 2;       // Track Ecken-Radius
          int ty1 = 80;          // Track 1 Y (Saege)
          int ty2 = 200;         // Track 2 Y (Absaugung)
          
          int knob_d = 58;       // Knob Durchmesser
          int knob_r = knob_d / 2;
          int knob_pad = 6;      // Abstand Knob zum Track-Rand
          int knob_y_off = (th - knob_d) / 2;  // Vertikal zentriert
          
          // Knob X-Positionen: links (AUS) und rechts (AN)
          int knob_left = tx + knob_pad;
          int knob_right = tx + tw - knob_d - knob_pad;
          int knob_travel = knob_right - knob_left;
          
          // Icon/Label Positionen im Track
          int icon_y_off = (th - 36) / 2;  // 36px Icon zentriert
          int label_off = 46;               // Label Offset nach Icon
          
          // =========================================
          // Hilfsfunktion: Knob-Position berechnen
          // Bei Animation: Interpolation ueber 5 Steps
          // anim_step 0 = idle (Endposition)
          // anim_step 1..5 = Zwischenpositionen
          // anim_dir 1 = nach rechts, -1 = nach links
          // =========================================
          
          // ---- SLIDER 1: SAEGE ----
          bool s1_on = id(sw_saege).state;
          int a1 = id(anim_step_1);
          int d1 = id(anim_dir_1);
          int knob_x1;
          if (a1 == 0) {
            knob_x1 = s1_on ? knob_right : knob_left;
          } else {
            // Animation: von Start zu Ziel interpolieren
            float progress = (float)a1 / 5.0f;
            if (d1 > 0) {
              knob_x1 = knob_left + (int)(progress * knob_travel);
            } else {
              knob_x1 = knob_right - (int)(progress * knob_travel);
            }
          }
          
          // Track zeichnen
          Color track_col1 = (s1_on || a1 > 0) ? col_track_on : col_track_off;
          // Wenn Animation nach AUS laeuft, Track noch teilweise gruen
          if (a1 > 0 && d1 < 0) {
            float fade = 1.0f - ((float)a1 / 5.0f);
            // Einfach: Track bleibt gruen waehrend Animation
            track_col1 = col_track_on;
            if (a1 >= 4) track_col1 = col_track_off;
          }
          // Track Hintergrund (Pill-Form: Kreise links+rechts + Rechteck mitte)
          it.filled_circle(tx + tr, ty1 + tr, tr, track_col1);
          it.filled_circle(tx + tw - tr, ty1 + tr, tr, track_col1);
          it.filled_rectangle(tx + tr, ty1, tw - th, th, track_col1);
          
          // Icon + Label im Track (gegenueber vom Knob)
          if (s1_on || (a1 > 0 && d1 > 0)) {
            // AN oder animiert nach AN: Icon+Label links
            it.image(tx + 18, ty1 + icon_y_off, id(imgSaege), col_white);
            it.print(tx + 18 + label_off, ty1 + tr, id(fnt22), col_white, TextAlign::CENTER_LEFT, "SAEGE");
          } else {
            // AUS: Icon+Label rechts
            it.image(tx + tw - 18 - 36 - label_off - 40, ty1 + icon_y_off, id(imgSaege), col_grey);
            it.print(tx + tw - 18 - 36, ty1 + tr, id(fnt22), col_grey, TextAlign::CENTER_RIGHT, "SAEGE");
          }
          
          // Knob (weisser Kreis)
          int kcx1 = knob_x1 + knob_r;
          int kcy1 = ty1 + knob_y_off + knob_r;
          it.filled_circle(kcx1, kcy1, knob_r, col_white);
          // Status-Text im Knob
          if (s1_on && a1 == 0) {
            it.print(kcx1, kcy1, id(fnt18), col_knob_on, TextAlign::CENTER, "AN");
          } else if (!s1_on && a1 == 0) {
            it.print(kcx1, kcy1, id(fnt18), col_knob_off, TextAlign::CENTER, "AUS");
          }
          
          // ---- Trennlinie ----
          it.horizontal_line(80, 178, 320, col_separator);
          
          // ---- SLIDER 2: ABSAUGUNG ----
          bool s2_on = id(sw_absaugung).state;
          int a2 = id(anim_step_2);
          int d2 = id(anim_dir_2);
          int knob_x2;
          if (a2 == 0) {
            knob_x2 = s2_on ? knob_right : knob_left;
          } else {
            float progress = (float)a2 / 5.0f;
            if (d2 > 0) {
              knob_x2 = knob_left + (int)(progress * knob_travel);
            } else {
              knob_x2 = knob_right - (int)(progress * knob_travel);
            }
          }
          
          Color track_col2 = (s2_on || a2 > 0) ? col_track_on : col_track_off;
          if (a2 > 0 && d2 < 0) {
            track_col2 = col_track_on;
            if (a2 >= 4) track_col2 = col_track_off;
          }
          it.filled_circle(tx + tr, ty2 + tr, tr, track_col2);
          it.filled_circle(tx + tw - tr, ty2 + tr, tr, track_col2);
          it.filled_rectangle(tx + tr, ty2, tw - th, th, track_col2);
          
          if (s2_on || (a2 > 0 && d2 > 0)) {
            it.image(tx + 18, ty2 + icon_y_off, id(imgAbsaugung), col_white);
            it.print(tx + 18 + label_off, ty2 + tr, id(fnt22), col_white, TextAlign::CENTER_LEFT, "ABSAUGUNG");
          } else {
            it.image(tx + tw - 18 - 36 - label_off - 80, ty2 + icon_y_off, id(imgAbsaugung), col_grey);
            it.print(tx + tw - 18 - 36, ty2 + tr, id(fnt22), col_grey, TextAlign::CENTER_RIGHT, "ABSAUGUNG");
          }
          
          int kcx2 = knob_x2 + knob_r;
          int kcy2 = ty2 + knob_y_off + knob_r;
          it.filled_circle(kcx2, kcy2, knob_r, col_white);
          if (s2_on && a2 == 0) {
            it.print(kcx2, kcy2, id(fnt18), col_knob_on, TextAlign::CENTER, "AN");
          } else if (!s2_on && a2 == 0) {
            it.print(kcx2, kcy2, id(fnt18), col_knob_off, TextAlign::CENTER, "AUS");
          }
          
          // ---- Footer: Wifi-Punkt ----
          if (id(${id_prefix}_wifi).has_state()) {
            Color wc = (id(${id_prefix}_wifi).state > -65) ? col_track_on : col_knob_off;
            it.filled_circle(240, 305, 4, wc);
          }

font:
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt28
    size: 28
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt22
    size: 22
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt18
    size: 18
    glyphs: "ANUSO "

color:
  # Hintergrund
  - id: bg_dark
    red: 4%
    green: 5%
    blue: 8%
  # Track AN (sattes Tuerkis)
  - id: col_track_on
    red: 10%
    green: 65%
    blue: 50%
  # Track AUS (dunkles Grau)
  - id: col_track_off
    red: 15%
    green: 17%
    blue: 20%
  # Weiss (Knob + Header)
  - id: col_white
    red: 100%
    green: 100%
    blue: 100%
  # Label-Grau (AUS-Zustand)
  - id: col_grey
    red: 50%
    green: 52%
    blue: 55%
  # Knob-Text AN (Tuerkis)
  - id: col_knob_on
    red: 10%
    green: 65%
    blue: 50%
  # Knob-Text AUS (dunkelgrau)
  - id: col_knob_off
    red: 45%
    green: 45%
    blue: 48%
  # Trennlinie
  - id: col_separator
    red: 18%
    green: 20%
    blue: 24%

image:
  - file: mdi:saw-blade
    id: imgSaege
    resize: 36x36
    type: TRANSPARENT_BINARY
  - file: mdi:fan
    id: imgAbsaugung
    resize: 36x36
    type: TRANSPARENT_BINARY

sensor:
  - platform: wifi_signal
    name: "${id_prefix}_wifi"
    id: "${id_prefix}_wifi"
    internal: true
    update_interval: 120s

binary_sensor:
  # Touch-Bereiche deckungsgleich mit den Tracks
  - platform: touchscreen
    id: touch_saege
    internal: true
    page_id: main_page
    x_min: 40
    x_max: 440
    y_min: 75
    y_max: 155
    on_press:
      - script.execute: toggle_switch1

  - platform: touchscreen
    id: touch_absaugung
    internal: true
    page_id: main_page
    x_min: 40
    x_max: 440
    y_min: 195
    y_max: 275
    on_press:
      - script.execute: toggle_switch2
