# ============================================
# S채gesteuerung - WT32-SC01 Display mit ESPHome
# Optimiert f체r minimale CPU-Last & schnelle Reaktion
#
# Nutzung als Remote-Package:
#   packages:
#     saege:
#       url: https://github.com/linbo24/wt32sc01-with-esphome
#       ref: main
#       files:
#         - saegesteuerung.yaml
# ============================================

substitutions:
  name: "saegesteuerung"
  friendly_name: "S채gesteuerung"
  id_prefix: "saege"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - display.page.show: main_page

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

psram:
  mode: quad
  speed: 80MHz

preferences:
  flash_write_interval: 60min

logger:
  level: WARN
  baud_rate: 0

api:

ota:
  - platform: esphome
    password: !secret esphome_ota_pw

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pw_iot
  power_save_mode: NONE
  manual_ip:
    static_ip: !secret ip_saegesteuerung
    gateway: !secret ip_iot_gateway
    subnet: !secret ip_iot_subnet
    dns1: !secret ip_iot_dns
  ap:
    ssid: "${name} Fallback"
    password: !secret esphome_fb_pw

switch:
  - platform: template
    name: "S채ge"
    id: sw_saege
    icon: "mdi:saw-blade"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - component.update: ${id_prefix}_display
    on_turn_off:
      - component.update: ${id_prefix}_display

  - platform: template
    name: "Absaugung"
    id: sw_absaugung
    icon: "mdi:fan"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - component.update: ${id_prefix}_display
    on_turn_off:
      - component.update: ${id_prefix}_display

script:
  - id: undim_script
    mode: restart
    then:
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 80%
      - delay: 30s
      - light.turn_on:
          id: ${id_prefix}_backlight
          brightness: 20%

  - id: toggle_switch1
    mode: single
    then:
      - switch.toggle: sw_saege

  - id: toggle_switch2
    mode: single
    then:
      - switch.toggle: sw_absaugung

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} Backlight"
    id: ${id_prefix}_backlight
    restore_mode: RESTORE_DEFAULT_OFF

i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

touchscreen:
  - platform: ft63x6
    id: ${id_prefix}_touch
    i2c_id: i2c_bus_intern
    interrupt_pin: GPIO39
    transform:
      swap_xy: true
      mirror_y: true
    on_touch:
      - script.execute: undim_script

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9xxx
    id: ${id_prefix}_display
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    invert_colors: false
    transform:
      swap_xy: true
    dimensions:
      width: 480
      height: 320
    update_interval: never
    pages:
      - id: main_page
        lambda: |-
          it.fill(bg_dark);
          
          // Header
          it.print(240, 28, id(fnt32), col_white, TextAlign::TOP_CENTER, "SAEGESTEUERUNG");
          
          // Button-Layout: zentriert, Platz fuer Status-Text rechts
          int pw = 300;
          int ph = 70;
          int px = 40;
          int py1 = 95;
          int py2 = 205;
          int sx = px + pw + 16;
          
          // === SAEGE ===
          if (id(sw_saege).state) {
            it.filled_rectangle(px, py1, pw, ph, col_mint);
            it.image(px + 20, py1 + 15, id(imgSaege), bg_dark);
            it.print(px + 72, py1 + 35, id(fnt28), bg_dark, TextAlign::CENTER_LEFT, "SAEGE");
            it.print(sx, py1 + 35, id(fnt22), col_mint, TextAlign::CENTER_LEFT, "AN");
          } else {
            it.rectangle(px, py1, pw, ph, col_mint);
            it.image(px + 20, py1 + 15, id(imgSaege), col_light_grey);
            it.print(px + 72, py1 + 35, id(fnt28), col_white, TextAlign::CENTER_LEFT, "SAEGE");
            it.print(sx, py1 + 35, id(fnt22), col_light_grey, TextAlign::CENTER_LEFT, "AUS");
          }
          
          // Trennlinie
          it.horizontal_line(60, 185, 360, col_dark_grey);
          
          // === ABSAUGUNG ===
          if (id(sw_absaugung).state) {
            it.filled_rectangle(px, py2, pw, ph, col_mint);
            it.image(px + 20, py2 + 15, id(imgAbsaugung), bg_dark);
            it.print(px + 72, py2 + 35, id(fnt28), bg_dark, TextAlign::CENTER_LEFT, "ABSAUGUNG");
            it.print(sx, py2 + 35, id(fnt22), col_mint, TextAlign::CENTER_LEFT, "AN");
          } else {
            it.rectangle(px, py2, pw, ph, col_mint);
            it.image(px + 20, py2 + 15, id(imgAbsaugung), col_light_grey);
            it.print(px + 72, py2 + 35, id(fnt28), col_white, TextAlign::CENTER_LEFT, "ABSAUGUNG");
            it.print(sx, py2 + 35, id(fnt22), col_light_grey, TextAlign::CENTER_LEFT, "AUS");
          }

font:
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt32
    size: 32
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 "
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt28
    size: 28
    glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
  - file:
      type: gfonts
      family: "Roboto"
      weight: bold
    id: fnt22
    size: 22
    glyphs: "ANUSO "

color:
  - id: bg_dark
    red: 4%
    green: 5%
    blue: 8%
  - id: col_mint
    red: 10%
    green: 74%
    blue: 61%
  - id: col_white
    red: 100%
    green: 100%
    blue: 100%
  - id: col_light_grey
    red: 65%
    green: 65%
    blue: 65%
  - id: col_dark_grey
    red: 25%
    green: 25%
    blue: 30%

image:
  - file: mdi:saw-blade
    id: imgSaege
    resize: 40x40
    type: BINARY
  - file: mdi:fan
    id: imgAbsaugung
    resize: 40x40
    type: BINARY

sensor:
  - platform: wifi_signal
    name: "${id_prefix}_wifi"
    id: "${id_prefix}_wifi"
    internal: true
    update_interval: 120s

binary_sensor:
  # Touch: nach swap_xy+mirror_y auf dem WT32-SC01 im Landscape:
  #   x = horizontal (0=links, 480=rechts)
  #   y = vertikal   (0=oben, 320=unten)
  # Button 1 (Saege):     x=30..350, y=85..175
  # Button 2 (Absaugung): x=30..350, y=195..285
  - platform: touchscreen
    id: touch_saege
    internal: true
    page_id: main_page
    x_min: 30
    x_max: 350
    y_min: 85
    y_max: 175
    on_press:
      - script.execute: toggle_switch1

  - platform: touchscreen
    id: touch_absaugung
    internal: true
    page_id: main_page
    x_min: 30
    x_max: 350
    y_min: 195
    y_max: 285
    on_press:
      - script.execute: toggle_switch2
